# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Bar API
tagline:          'Rest API for sharing music'
description:      'Bar API is a RESTful API that allows users to share music with one another with their front-ends.'
url:              https://damofd.github.io
baseurl:          /Bar-API/

author:
  name:           'DamoFD'
  url:            https://linkedin.com/in/damion-voshall

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/DamoFD/Bar-API
